CREATE TABLE IF NOT EXISTS product_catalog_import_jobs (
    id VARCHAR(36) PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    file_name VARCHAR(255) NOT NULL DEFAULT '',
    file_size BIGINT NOT NULL DEFAULT 0,
    fingerprint VARCHAR(128) NOT NULL DEFAULT '',
    uploaded_bytes BIGINT NOT NULL DEFAULT 0,
    chunk_size BIGINT NOT NULL DEFAULT 0,
    archive_path VARCHAR(1024) NOT NULL DEFAULT '',
    extracted_path VARCHAR(1024) NOT NULL DEFAULT '',
    options_json LONGTEXT,
    preview_json LONGTEXT,
    worker_token VARCHAR(36) NOT NULL DEFAULT '',
    last_sku VARCHAR(100) NOT NULL DEFAULT '',
    total_products INT NOT NULL DEFAULT 0,
    processed_products INT NOT NULL DEFAULT 0,
    created_products INT NOT NULL DEFAULT 0,
    updated_products INT NOT NULL DEFAULT 0,
    skipped_products INT NOT NULL DEFAULT 0,
    failed_products INT NOT NULL DEFAULT 0,
    restored_files INT NOT NULL DEFAULT 0,
    message VARCHAR(255) NOT NULL DEFAULT '',
    error LONGTEXT,
    created_by_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NULL,
    updated_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    INDEX idx_product_catalog_import_jobs_status (status),
    INDEX idx_product_catalog_import_jobs_fingerprint (fingerprint),
    INDEX idx_product_catalog_import_jobs_worker_token (worker_token),
    INDEX idx_product_catalog_import_jobs_last_sku (last_sku),
    INDEX idx_product_catalog_import_jobs_created_by_id (created_by_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
