CREATE TABLE IF NOT EXISTS product_image_autofill_jobs (
    id VARCHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL,
    brand VARCHAR(100) NOT NULL DEFAULT '',
    category_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    include_descendants TINYINT(1) NOT NULL DEFAULT 0,
    product_status VARCHAR(16) NOT NULL DEFAULT 'all',
    batch_size BIGINT NOT NULL DEFAULT 250,
    max_product_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_product_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    image_version VARCHAR(32) NOT NULL DEFAULT '',
    worker_token VARCHAR(36) NOT NULL DEFAULT '',
    total BIGINT NOT NULL DEFAULT 0,
    processed BIGINT NOT NULL DEFAULT 0,
    updated BIGINT NOT NULL DEFAULT 0,
    skipped BIGINT NOT NULL DEFAULT 0,
    failed BIGINT NOT NULL DEFAULT 0,
    message VARCHAR(255) NOT NULL DEFAULT '',
    error LONGTEXT,
    created_by_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    KEY idx_product_image_autofill_jobs_status (status),
    KEY idx_product_image_autofill_jobs_brand (brand),
    KEY idx_product_image_autofill_jobs_category_id (category_id),
    KEY idx_product_image_autofill_jobs_worker_token (worker_token),
    KEY idx_product_image_autofill_jobs_created_by_id (created_by_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
